# -*- coding: utf-8 -*-
"""MADT7104_29Mar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pi226g5znwUJRJl6_J3YZTAkAgwCWEK
"""

import streamlit as st
import random

st.title('Test Streamlit')
st.wrute('Hello World!')

if st.button('Gennerate Randon Number'):
  random_munber = random_randint(1,100)
  st.write(f'Random Number: {random_munber}')